"""Template strings for the skeleton generator.

Separated from skeleton.py's CLI / glue per design/skeleton-
generator-sketch-01.md. Five template strings — one per stub file —
rendered with standard `str.format` interpolation against a shared
context dict built in skeleton.py.

Interpolation placeholders (all fields required unless noted):

- `{work_id}`           — snake_case id, used as module / file prefix
- `{title}`             — human-readable title for docstrings
- `{date}`              — ISO date (YYYY-MM-DD) of generation
- `{entity_constants}`  — multi-line block of Entity(...) assignments
- `{character_defs}`    — multi-line block of Character(...) assignments
- `{character_id_list}` — comma-separated character id tuple literal
"""
from __future__ import annotations


SUBSTRATE_STUB = '''"""
{work_id}.py — {title} substrate encoding (skeleton).

Skeletal stub generated by story_engine.tools.skeleton on {date}.
Author responsibility: fill in ENTITIES, FABULA, BRANCHES, RULES,
DESCRIPTIONS per substrate-sketch-05, identity-and-realization-
sketch-01, inference-model-sketch-01.

Running this encoding's verifier before authoring content produces
a "skeletal encoding" advisory per SG4; that advisory is the
contract that tells the author which records are still missing.
"""
from __future__ import annotations

from story_engine.core.substrate import (
    Entity, Event, Prop,
    Branch, BranchKind, CANONICAL, CANONICAL_LABEL,
    Slot, Confidence, Diegetic, Narrative,
    Held, KnowledgeEffect, WorldEffect,
    SjuzhetEntry, Disclosure,
    Description, AnchorRef, Attention, anchor_event, anchor_desc,
    IDENTITY_PREDICATE,
    Rule,
)


# ---------------------------------------------------------------------------
# Entities
# ---------------------------------------------------------------------------

{entity_constants}

ENTITIES = [
    {character_id_list}
]


# ---------------------------------------------------------------------------
# Fabula (events) — TODO: author here per substrate-sketch-05
# ---------------------------------------------------------------------------

FABULA: list = []


# ---------------------------------------------------------------------------
# Branches — canonical only until the author adds contested /
# counterfactual / draft branches.
# ---------------------------------------------------------------------------

ALL_BRANCHES = {{
    CANONICAL_LABEL: CANONICAL,
}}


# ---------------------------------------------------------------------------
# Rules (inference-model-sketch-01) — TODO: author compound-predicate
# rules here if the encoding needs them.
# ---------------------------------------------------------------------------

RULES: tuple = ()


# ---------------------------------------------------------------------------
# Descriptions (descriptions-sketch-01) — TODO: author interpretive
# descriptions here.
# ---------------------------------------------------------------------------

DESCRIPTIONS: list = []
'''


DRAMATIC_STUB = '''"""
{work_id}_dramatic.py — {title} Dramatic dialect encoding (skeleton).

Skeletal stub generated by story_engine.tools.skeleton on {date}.
Author responsibility: fill in ARGUMENTS, THROUGHLINES (owners +
subject), SCENES, BEATS, STAKES; wire `STORY.throughline_ids` /
`character_ids` / etc. to reference authored records.

Four Throughline stubs follow the Dramatica-8 convention (OS, MC,
IC, RS); `owners` start as (THROUGHLINE_OWNER_NONE,) placeholders
that the author replaces with character ids or abstract sentinels
(THROUGHLINE_OWNER_SITUATION / THROUGHLINE_OWNER_RELATIONSHIP).

Per dramatic-sketch-01 M1, a Story may have zero or more Arguments;
the stub ships with ARGUMENTS empty.
"""
from __future__ import annotations

from story_engine.core.dramatic import (
    Story, Argument, Throughline, Character, Beat, Scene, Stakes,
    ArgumentContribution, SceneAdvancement, StakesOwner,
    ResolutionDirection, ArgumentSide, StakesOwnerKind,
    THROUGHLINE_OWNER_NONE,
    THROUGHLINE_OWNER_SITUATION, THROUGHLINE_OWNER_RELATIONSHIP,
)


# ============================================================================
# Characters (shape; author may add function_labels later)
# ============================================================================

{character_defs}

CHARACTERS = (
    {character_id_list}
)


# ============================================================================
# Throughlines — Dramatica-8 standard four; `owners` placeholder.
# ============================================================================

T_os = Throughline(
    id="T_os",
    role_label="Overall Story",
    owners=(THROUGHLINE_OWNER_SITUATION,),  # TODO: replace with character ids
    subject="TODO: name the OS subject",
)

T_mc = Throughline(
    id="T_mc",
    role_label="Main Character",
    owners=(THROUGHLINE_OWNER_NONE,),  # TODO: replace with MC character id
    subject="TODO: name the MC throughline subject",
)

T_ic = Throughline(
    id="T_ic",
    role_label="Influence Character",
    owners=(THROUGHLINE_OWNER_NONE,),  # TODO: replace with IC character id
    subject="TODO: name the IC throughline subject",
)

T_rs = Throughline(
    id="T_rs",
    role_label="Relationship Story",
    owners=(THROUGHLINE_OWNER_RELATIONSHIP,),
    subject="TODO: name the RS subject",
)

THROUGHLINES = (T_os, T_mc, T_ic, T_rs)


# ============================================================================
# Arguments, Scenes, Beats, Stakes — all TODO
# ============================================================================

ARGUMENTS: tuple = ()
SCENES: tuple = ()
BEATS: tuple = ()
STAKES: tuple = ()


# ============================================================================
# Story
# ============================================================================

STORY = Story(
    id="S_{work_id}",
    title="{title}",
    character_function_template_id="dramatica-8",
    argument_ids=tuple(a.id for a in ARGUMENTS),
    throughline_ids=tuple(t.id for t in THROUGHLINES),
    character_ids=tuple(c.id for c in CHARACTERS),
    scene_ids=tuple(s.id for s in SCENES),
    beat_ids=tuple(b.id for b in BEATS),
    stakes_ids=tuple(s.id for s in STAKES),
)
'''


TEMPLATE_STUB = '''"""
{work_id}_dramatica_complete.py — {title} Dramatica Template
encoding (skeleton).

Skeletal stub generated by story_engine.tools.skeleton on {date}.
Author responsibility: fill in DomainAssignments (4 per Story; one
per Throughline × Domain mapping), DynamicStoryPoints (6 axes per
Story: resolve, growth, approach, limit, outcome, judgment),
Signposts (4 per Throughline), ThematicPicks, CharacterElement-
Assignments, Story_goal, Story_consequence — per dramatica-
template-sketch-01 Q1-Q10.

All tuples start empty; the verifier emits per-check advisories
naming what's still missing.
"""
from __future__ import annotations

from story_engine.core.dramatica_template import (
    DomainAssignment, DynamicStoryPoint, DSPAxis,
    Domain, Resolve, Growth, Approach, Limit, Outcome, Judgment,
    Signpost, ThematicPicks, CharacterElementAssignment,
)

from story_engine.encodings.{work_id}_dramatic import STORY


# ============================================================================
# Domain assignments (4 per Story, one per Throughline)
# ============================================================================

DOMAIN_ASSIGNMENTS: tuple = ()  # TODO: author 4 DomainAssignment records


# ============================================================================
# Dynamic Story Points (6 axes — resolve, growth, approach, limit,
# outcome, judgment)
# ============================================================================

DYNAMIC_STORY_POINTS: tuple = ()  # TODO: author 6 DynamicStoryPoint records


# ============================================================================
# Signposts (4 per Throughline = 16 per Story)
# ============================================================================

SIGNPOSTS: tuple = ()  # TODO: author Signpost records


# ============================================================================
# Thematic picks
# ============================================================================

THEMATIC_PICKS: tuple = ()  # TODO: author ThematicPick records


# ============================================================================
# Character-element assignments
# ============================================================================

CHARACTER_ELEMENT_ASSIGNMENTS: tuple = ()  # TODO: author per Dramatica-8


# ============================================================================
# Story goal / consequence — free-form strings (author-owned)
# ============================================================================

STORY_GOAL: str | None = None  # TODO: one-sentence description of the OS goal
STORY_CONSEQUENCE: str | None = None  # TODO: one-sentence consequence of failure
'''


LOWERINGS_STUB = '''"""
{work_id}_lowerings.py — Lowering bindings: {title} Dramatic ↔
substrate (skeleton).

Skeletal stub generated by story_engine.tools.skeleton on {date}.
Author responsibility: author Lowering records that bind upper-
dialect records (Character, Scene, Throughline) to substrate
records (Entity, Event), per lowering-record-sketch-01.

All Lowerings in an ACTIVE encoding should follow L1 — Realization
coupling only; Characterization and Claim couplings live in the
verifier surface, not here.
"""
from __future__ import annotations

from story_engine.core.lowering import (
    Lowering, CrossDialectRef, cross_ref,
    Annotation, AnnotationReview, PositionRange,
    LoweringStatus,
    ATTENTION_STRUCTURAL, ATTENTION_INTERPRETIVE,
)


# ============================================================================
# Lowerings — TODO: author here
# ============================================================================

LOWERINGS: tuple = ()
'''


VERIFICATION_STUB = '''"""
{work_id}_dramatica_complete_verification.py — cross-boundary
verifier at the dramatica-complete → substrate coupling boundary
(skeleton).

Skeletal stub generated by story_engine.tools.skeleton on {date}.
Registers the canonical Template checks; each check skips until
the author adds ACTIVE Lowerings and fills the Template records
referenced above.

`run()` emits a single "skeletal encoding" StructuralAdvisory
listing which records are still empty, so the author's first
verifier invocation against this encoding tells them exactly what
to fill.
"""
from __future__ import annotations

from story_engine.core.verification import (
    StructuralAdvisory, SEVERITY_NOTED,
)
from story_engine.core.lowering import cross_ref


# The advisor_id uniquely identifies the "skeletal encoding" advisory,
# distinguishing it from any other advisory a verifier might emit.
SKELETAL_ADVISOR_ID = "skeleton:{work_id}"


def run(advised_at_τ_a: int = 0):
    """Entry point — run the verifier against this encoding.

    Until content is authored (see TODOs in the sibling stub files),
    this emits a single StructuralAdvisory naming what's missing.
    Once content is authored, replace this skeleton run() with the
    full check registration pattern — see e.g.
    oedipus_dramatica_complete_verification.run() for reference.
    """
    advisory = StructuralAdvisory(
        advisor_id=SKELETAL_ADVISOR_ID,
        advised_at_τ_a=advised_at_τ_a,
        severity=SEVERITY_NOTED,
        comment=(
            "Skeletal {work_id} encoding — no Template records "
            "authored yet. See TODOs in {work_id}_dramatic.py, "
            "{work_id}_dramatica_complete.py, {work_id}_lowerings.py, "
            "and {work_id}.py for the fill-in contract. Replace this "
            "run() with full check registration once content is "
            "authored — see oedipus_dramatica_complete_verification.run()"
            " as the reference pattern."
        ),
        scope=(cross_ref("dramatic", "S_{work_id}"),),
    )
    return [advisory]


if __name__ == "__main__":
    results = run()
    print(f"{{len(results)}} advisory emitted.")
    for r in results:
        print(f"  [{{r.advisor_id}}] {{r.comment}}")
'''


TEMPLATES = {
    "{work_id}.py": SUBSTRATE_STUB,
    "{work_id}_dramatic.py": DRAMATIC_STUB,
    "{work_id}_dramatica_complete.py": TEMPLATE_STUB,
    "{work_id}_lowerings.py": LOWERINGS_STUB,
    "{work_id}_dramatica_complete_verification.py": VERIFICATION_STUB,
}
