"""
and_then_there_were_none_dramatica_complete_verification.py — cross-boundary
verifier at the dramatica-complete → substrate coupling boundary
(skeleton).

Skeletal stub generated by story_engine.tools.skeleton on 2026-04-18.
Registers the canonical Template checks; each check skips until
the author adds ACTIVE Lowerings and fills the Template records
referenced above.

`run()` emits a single "skeletal encoding" StructuralAdvisory
listing which records are still empty, so the author's first
verifier invocation against this encoding tells them exactly what
to fill.
"""
from __future__ import annotations

from story_engine.core.verification import (
    StructuralAdvisory, SEVERITY_NOTED,
)
from story_engine.core.lowering import cross_ref


# The advisor_id uniquely identifies the "skeletal encoding" advisory,
# distinguishing it from any other advisory a verifier might emit.
SKELETAL_ADVISOR_ID = "skeleton:and_then_there_were_none"


def run(advised_at_τ_a: int = 0):
    """Entry point — run the verifier against this encoding.

    Until content is authored (see TODOs in the sibling stub files),
    this emits a single StructuralAdvisory naming what's missing.
    Once content is authored, replace this skeleton run() with the
    full check registration pattern — see e.g.
    oedipus_dramatica_complete_verification.run() for reference.
    """
    advisory = StructuralAdvisory(
        advisor_id=SKELETAL_ADVISOR_ID,
        advised_at_τ_a=advised_at_τ_a,
        severity=SEVERITY_NOTED,
        comment=(
            "Skeletal and_then_there_were_none encoding — no Template records "
            "authored yet. See TODOs in and_then_there_were_none_dramatic.py, "
            "and_then_there_were_none_dramatica_complete.py, and_then_there_were_none_lowerings.py, "
            "and and_then_there_were_none.py for the fill-in contract. Replace this "
            "run() with full check registration once content is "
            "authored — see oedipus_dramatica_complete_verification.run()"
            " as the reference pattern."
        ),
        scope=(cross_ref("dramatic", "S_and_then_there_were_none"),),
    )
    return [advisory]


if __name__ == "__main__":
    results = run()
    print(f"{len(results)} advisory emitted.")
    for r in results:
        print(f"  [{r.advisor_id}] {r.comment}")
