"""
and_then_there_were_none_dramatic.py — And Then There Were None Dramatic dialect encoding (skeleton).

Skeletal stub generated by story_engine.tools.skeleton on 2026-04-18.
Author responsibility: fill in ARGUMENTS, THROUGHLINES (owners +
subject), SCENES, BEATS, STAKES; wire `STORY.throughline_ids` /
`character_ids` / etc. to reference authored records.

Four Throughline stubs follow the Dramatica-8 convention (OS, MC,
IC, RS); `owners` start as (THROUGHLINE_OWNER_NONE,) placeholders
that the author replaces with character ids or abstract sentinels
(THROUGHLINE_OWNER_SITUATION / THROUGHLINE_OWNER_RELATIONSHIP).

Per dramatic-sketch-01 M1, a Story may have zero or more Arguments;
the stub ships with ARGUMENTS empty.
"""
from __future__ import annotations

from story_engine.core.dramatic import (
    Story, Argument, Throughline, Character, Beat, Scene, Stakes,
    ArgumentContribution, SceneAdvancement, StakesOwner,
    ResolutionDirection, ArgumentSide, StakesOwnerKind,
    THROUGHLINE_OWNER_NONE,
    THROUGHLINE_OWNER_SITUATION, THROUGHLINE_OWNER_RELATIONSHIP,
)


# ============================================================================
# Characters (shape; author may add function_labels later)
# ============================================================================

C_wargrave = Character(id="wargrave", name="Justice Wargrave")
C_vera = Character(id="vera", name="Vera Claythorne")
C_lombard = Character(id="lombard", name="Philip Lombard")
C_emily = Character(id="emily", name="Emily Brent")
C_macarthur = Character(id="macarthur", name="General Macarthur")
C_armstrong = Character(id="armstrong", name="Dr Armstrong")
C_blore = Character(id="blore", name="William Blore")
C_marston = Character(id="marston", name="Anthony Marston")
C_rogers = Character(id="rogers", name="Thomas Rogers")
C_mrs_rogers = Character(id="mrs_rogers", name="Ethel Rogers")

CHARACTERS = (
    C_wargrave, C_vera, C_lombard, C_emily, C_macarthur, C_armstrong, C_blore, C_marston, C_rogers, C_mrs_rogers
)


# ============================================================================
# Throughlines — Dramatica-8 standard four; `owners` placeholder.
# ============================================================================

T_os = Throughline(
    id="T_os",
    role_label="Overall Story",
    owners=(THROUGHLINE_OWNER_SITUATION,),  # TODO: replace with character ids
    subject="TODO: name the OS subject",
)

T_mc = Throughline(
    id="T_mc",
    role_label="Main Character",
    owners=(THROUGHLINE_OWNER_NONE,),  # TODO: replace with MC character id
    subject="TODO: name the MC throughline subject",
)

T_ic = Throughline(
    id="T_ic",
    role_label="Influence Character",
    owners=(THROUGHLINE_OWNER_NONE,),  # TODO: replace with IC character id
    subject="TODO: name the IC throughline subject",
)

T_rs = Throughline(
    id="T_rs",
    role_label="Relationship Story",
    owners=(THROUGHLINE_OWNER_RELATIONSHIP,),
    subject="TODO: name the RS subject",
)

THROUGHLINES = (T_os, T_mc, T_ic, T_rs)


# ============================================================================
# Arguments, Scenes, Beats, Stakes — all TODO
# ============================================================================

ARGUMENTS: tuple = ()
SCENES: tuple = ()
BEATS: tuple = ()
STAKES: tuple = ()


# ============================================================================
# Story
# ============================================================================

STORY = Story(
    id="S_and_then_there_were_none",
    title="And Then There Were None",
    character_function_template_id="dramatica-8",
    argument_ids=tuple(a.id for a in ARGUMENTS),
    throughline_ids=tuple(t.id for t in THROUGHLINES),
    character_ids=tuple(c.id for c in CHARACTERS),
    scene_ids=tuple(s.id for s in SCENES),
    beat_ids=tuple(b.id for b in BEATS),
    stakes_ids=tuple(s.id for s in STAKES),
)
