"""
and_then_there_were_none_lowerings.py — Lowering bindings: And Then There Were None Dramatic ↔
substrate (skeleton).

Skeletal stub generated by story_engine.tools.skeleton on 2026-04-18.
Author responsibility: author Lowering records that bind upper-
dialect records (Character, Scene, Throughline) to substrate
records (Entity, Event), per lowering-record-sketch-01.

All Lowerings in an ACTIVE encoding should follow L1 — Realization
coupling only; Characterization and Claim couplings live in the
verifier surface, not here.
"""
from __future__ import annotations

from story_engine.core.lowering import (
    Lowering, CrossDialectRef, cross_ref,
    Annotation, AnnotationReview, PositionRange,
    LoweringStatus,
    ATTENTION_STRUCTURAL, ATTENTION_INTERPRETIVE,
)


# ============================================================================
# Lowerings — TODO: author here
# ============================================================================

LOWERINGS: tuple = ()
