"""
and_then_there_were_none.py — And Then There Were None substrate encoding (skeleton).

Skeletal stub generated by story_engine.tools.skeleton on 2026-04-18.
Author responsibility: fill in ENTITIES, FABULA, BRANCHES, RULES,
DESCRIPTIONS per substrate-sketch-05, identity-and-realization-
sketch-01, inference-model-sketch-01.

Running this encoding's verifier before authoring content produces
a "skeletal encoding" advisory per SG4; that advisory is the
contract that tells the author which records are still missing.

============================================================================
Sixth encoding — rationale and starting direction
============================================================================

Agatha Christie's *And Then There Were None* (1939). Selected as the
corpus's sixth encoding from state-of-play-02's "maybe-next" list
and the first real use of the skeleton generator
(scheduling-act-utterance-sketch-01 ships the tool as SG4).

Why this work:

- **Multi-suspect mystery.** The corpus has an *inverted* mystery
  (Ackroyd — the killer narrates) but no canonical whodunit. Ten
  strangers on an island, elimination by nursery rhyme, one of
  them is the killer.
- **Ensemble cast.** 10 characters vs. Rocky's 8 and Oedipus's 7.
  Stress-tests the Dramatica-8 function assignment across more
  bodies than function slots — some characters must double up or
  be Protagonist/Antagonist candidates.
- **Discrete-elimination Timelock.** Rocky's Timelock is calendar-
  based; Rashomon's testimonies' Timelocks are scheduled climaxes.
  Christie's is structural: ten-then-nine-then-eight-etc, each
  death narrowing the pool. Candidate LT-vocabulary probe for
  pressure-shape-taxonomy: does elimination-shaped-timelock
  register through the existing LT8/LT9 machinery, or does it
  need a new predicate family?

Anticipated DSP axis settings (subject to the probe's verdict):

- **DSP_limit = Timelock** (countdown-by-elimination).
- **DSP_outcome = Failure** (no one "wins" — nine die, the killer
  also dies by design).
- **DSP_judgment = Bad** (for any MC candidate — none escape).
- **DSP_approach = Do-er** for most candidates — the survival
  arc is about action.
- **DSP_resolve** — depends on which character anchors the MC
  throughline; contested choice (Vera is the conventional read,
  Wargrave the subversive read).
- **DSP_growth** — TBD.

MC/IC designation is open. Conventional read: **Vera as MC**,
**Wargrave as IC** (the unseen puppeteer whose judgments drive
Vera's mental collapse). Subversive read: **Wargrave as MC**
(the killer IS the protagonist in a structural sense, per the
epilogue's confession). Encoding decision deferred until the
probe weighs in on both readings.

Authoring pending:

- Substrate events: arrivals, dinner scene, gramophone accusation,
  ten deaths in sequence, post-death island states, epilogue
  confession. Estimated 30–50 events.
- Branches: possibly none (unlike Rashomon, the novel asserts a
  single canonical reading via the epilogue). Single canonical
  branch is the starting assumption.
- Rules: identity rules for "accused of murder" compound
  predicates? Probably one rule per accusation-discovery-pair.
- Dramatic layer: 4 throughlines, 10 character function
  assignments, ~15 scenes (gathering, accusation, 10 deaths,
  resolution), beats per throughline.
- Template layer: DomainAssignments, DSPs (per anticipated
  settings above), Signposts, CharacterElementAssignments.
- Lowerings: Character → Entity, Scene → Event-sets.
- Verification: replace the skeleton's run() with the canonical
  9-check pattern per oedipus_dramatica_complete_verification.py.

Probe expectations once authored (the encoding's contract):

- First canonical whodunit → MN2 (concealment-asymmetry, from
  event-manipulation-taxonomy-sketch-01) should fire differently
  than Ackroyd's inverted-mystery pattern. Possibly a new MN-
  predicate for multi-suspect-concealment.
- Discrete-elimination Timelock → LT8/LT9 probe. May surface a
  new scheduling-act vocabulary beyond scheduling-act-utterance-
  sketch-01's `scheduled_*` / `requested_*` (e.g., `counted_*`
  or `enumerated_*`).
- Dramatica-8 character-function assignment under cast-pressure
  → Stress case for the verifier's slot_unfilled / slot_overfilled
  observations from the dramatic dialect.
"""
from __future__ import annotations

from story_engine.core.substrate import (
    Entity, Event, Prop,
    Branch, BranchKind, CANONICAL, CANONICAL_LABEL,
    Slot, Confidence, Diegetic, Narrative,
    Held, KnowledgeEffect, WorldEffect,
    SjuzhetEntry, Disclosure,
    Description, AnchorRef, Attention, anchor_event, anchor_desc,
    IDENTITY_PREDICATE,
    Rule,
)


# ---------------------------------------------------------------------------
# Entities
# ---------------------------------------------------------------------------

wargrave = Entity(id="wargrave", name="Justice Wargrave", kind="agent")
vera = Entity(id="vera", name="Vera Claythorne", kind="agent")
lombard = Entity(id="lombard", name="Philip Lombard", kind="agent")
emily = Entity(id="emily", name="Emily Brent", kind="agent")
macarthur = Entity(id="macarthur", name="General Macarthur", kind="agent")
armstrong = Entity(id="armstrong", name="Dr Armstrong", kind="agent")
blore = Entity(id="blore", name="William Blore", kind="agent")
marston = Entity(id="marston", name="Anthony Marston", kind="agent")
rogers = Entity(id="rogers", name="Thomas Rogers", kind="agent")
mrs_rogers = Entity(id="mrs_rogers", name="Ethel Rogers", kind="agent")

ENTITIES = [
    wargrave, vera, lombard, emily, macarthur, armstrong, blore, marston, rogers, mrs_rogers
]


# ---------------------------------------------------------------------------
# Fabula (events) — TODO: author here per substrate-sketch-05
# ---------------------------------------------------------------------------

FABULA: list = []


# ---------------------------------------------------------------------------
# Branches — canonical only until the author adds contested /
# counterfactual / draft branches.
# ---------------------------------------------------------------------------

ALL_BRANCHES = {
    CANONICAL_LABEL: CANONICAL,
}


# ---------------------------------------------------------------------------
# Rules (inference-model-sketch-01) — TODO: author compound-predicate
# rules here if the encoding needs them.
# ---------------------------------------------------------------------------

RULES: tuple = ()


# ---------------------------------------------------------------------------
# Descriptions (descriptions-sketch-01) — TODO: author interpretive
# descriptions here.
# ---------------------------------------------------------------------------

DESCRIPTIONS: list = []
